// Generated by CoffeeScript 1.6.3
(function() {
  var Agent, async, method;

  Agent = require('../models/agentModel');

  async = require('async');

  method = {
    GET: function(req, res, next) {
      var num, opts, page, query, _id;
      if ((_id = req.params._id)) {
        if (_id === 'all') {
          return Agent.find({}, function(err, docs) {
            return res.send(docs);
          });
        }
        return Agent.findById(_id, function(err, doc) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(doc);
        });
      } else {
        page = (query = req.query).page || 1;
        num = query.num || 10;
        opts = {
          skip: (page - 1) * num,
          limit: num,
          sort: '-_id'
        };
        return async.auto({
          count: function(cb) {
            return Agent.count({}, cb);
          },
          data: function(cb) {
            return Agent.find({}, null, opts, cb);
          }
        }, function(err, rst) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send({
            totalPage: Math.ceil(rst.count / num),
            list: rst.data
          });
        });
      }
    },
    POST: function(req, res, next) {
      var _id;
      delete req.body._id;
      if ((_id = req.params._id)) {
        return Agent.findByIdAndUpdate(_id, req.body, function(err) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(200);
        });
      } else {
        return async.auto({
          count: function(cb) {
            return Agent.count({
              name: req.body.name
            }, cb);
          },
          save: [
            'count', function(cb, rst) {
              if (rst.count > 0) {
                return res.send(500, '代理商已经存在');
              }
              return Agent.create(req.body, cb);
            }
          ]
        }, function(err, rst) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(200);
        });
      }
    }
  };

  module.exports = function(req, res, next) {
    var e, _ref;
    try {
      if ((_ref = req.user.role) !== 'leader' && _ref !== 'admin') {
        return res.send(403);
      }
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      console.log(e);
      return res.send(405);
    }
  };

}).call(this);
