// Generated by CoffeeScript 1.6.3
(function() {
  var Area, async, method;

  Area = require('../models/areaModel');

  async = require('async');

  method = {
    GET: function(req, res, next) {
      var condition, num, opts, page, query, _id;
      if ((_id = req.params._id)) {
        return Area.findById(_id, function(err, doc) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(doc);
        });
      } else {
        condition = {
          parent: (query = req.query).parent
        };
        num = query.num || 10;
        page = query.page || 1;
        opts = {
          skip: (page - 1) * num,
          limit: num
        };
        return async.auto({
          count: function(cb) {
            return Area.count(condition, cb);
          },
          list: function(cb) {
            return Area.find(condition, null, opts, cb);
          }
        }, function(err, rst) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send({
            totalPage: Math.ceil(rst.count / num),
            list: rst.list
          });
        });
      }
    },
    POST: function(req, res, next) {
      var _id;
      _id = req.body._id;
      delete req.body._id;
      if (_id) {
        return Area.findByIdAndUpdate(_id, req.body, function(err, doc) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(200);
        });
      } else {
        return Area.create(req.body, function(err, doc) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(200);
        });
      }
    }
  };

  module.exports = function(req, res, next) {
    var e, _ref;
    try {
      if ((_ref = req.user.role) !== 'leader' && _ref !== 'admin') {
        return res.send(403);
      }
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      console.log(e);
      return res.send(405);
    }
  };

}).call(this);
