// Generated by CoffeeScript 1.7.1
(function() {
  var Client, helper, method;

  Client = require('../models/clientModel');

  helper = require('../commons/helper');

  method = {
    GET: function(req, res, next) {
      if (req.params._id) {
        return res.send(404);
      } else {
        return helper.getPage(Client, req.query, function(err, data) {
          return res.send(data);
        });
      }
    },
    POST: function(req, res, next) {
      delete req.body._id;
      if (req.params._id) {
        return Client.findByIdAndUpdate(req.params._id, req.body, function(err, doc) {
          if (err) {
            return next(err);
          }
          return res.send(200);
        });
      } else {
        return Client.create(req.body, function(err) {
          if (err) {
            return next(err);
          }
          return res.send(200);
        });
      }
    }
  };

  module.exports = function(req, res, next) {
    var e;
    try {
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      console.log(e);
      return res.send(405);
    }
  };

}).call(this);

//# sourceMappingURL=client.map
