// Generated by CoffeeScript 1.7.1
var Client, Project, helper, method;

Client = require('../models/clientModel');

Project = require('../models/projectModel');

helper = require('../commons/helper');

method = {
  GET: function(req, res, next) {
    if (req.params._id) {
      return res.send(404);
    } else {
      if (req.query.s) {
        return Client.find({
          'name': new RegExp(req.query.s, 'i')
        }, null, {
          limit: 10
        }, function(err, docs) {
          return res.send(docs);
        });
      } else {
        return helper.getPage(Client, req.query, function(err, data) {
          return res.send(data);
        });
      }
    }
  },
  POST: function(req, res, next) {
    delete req.body._id;
    if (req.params._id) {
      return Client.findByIdAndUpdate(req.params._id, req.body, function(err, doc) {
        if (err) {
          return next(err);
        }
        Project.update({
          'client._id': doc._id
        }, {
          'client.name': doc.name
        }, {
          multi: true
        }, function(err, num) {
          if (err) {
            return console.log(err);
          }
        });
        return res.send(200);
      });
    } else {
      return Client.findOne({
        name: req.body.name
      }, function(err, doc) {
        if (doc) {
          return res.send(400, '客户已经存在');
        }
        return Client.create(req.body, function(err) {
          if (err) {
            return next(err);
          }
          return res.send(200);
        });
      });
    }
  }
};

module.exports = function(req, res, next) {
  var e;
  try {
    return method[req.method](req, res, next);
  } catch (_error) {
    e = _error;
    console.log(e);
    return res.send(405);
  }
};

//# sourceMappingURL=client.map
