// Generated by CoffeeScript 1.7.1
var Product, Project, method, moment;

Project = require('../models/projectModel');

Product = require('../models/productModel');

moment = require('moment');

method = {
  GET: function(req, res, next) {
    var condition, opts, query;
    condition = JSON.parse((query = req.query).condition);
    if (req.user.role === 'supporter') {
      condition['supporter._id'] = req.user._id;
    }
    if (condition.sOrderDate) {
      condition.orderDate = condition.orderDate || {};
      condition.orderDate.$gte = condition.sOrderDate;
      delete condition.sOrderDate;
    }
    if (condition.eOrderDate) {
      condition.orderDate = condition.orderDate || {};
      condition.orderDate.$lte = condition.eOrderDate;
      delete condition.eOrderDate;
    }
    opts = {
      sort: '_id'
    };
    return Project.find(condition, null, opts, function(err, docs) {
      if (err) {
        return next(err);
      }
      return Product.find({}, function(err, products) {
        var p, pp, ppp, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
        for (_i = 0, _len = docs.length; _i < _len; _i++) {
          p = docs[_i];
          p.products = JSON.parse(JSON.stringify(products));
          _ref = p.agent.products;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            pp = _ref[_j];
            _ref1 = p.products;
            for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
              ppp = _ref1[_k];
              if (pp._id.toString() === ppp._id.toString()) {
                if (pp.num) {
                  ppp.num = pp.num + pp.unit;
                }
              }
            }
          }
        }
        res.attachment('export.xls');
        return res.render('export', {
          data: docs,
          products: products,
          moment: moment
        });
      });
    });
  }
};

module.exports = function(req, res, next) {
  var e;
  try {
    return method[req.method](req, res, next);
  } catch (_error) {
    e = _error;
    console.log(e);
    return res.send(405);
  }
};
