// Generated by CoffeeScript 1.7.1
var Agent, Product, method, _;

Product = require('../models/productModel');

Agent = require('../models/agentModel');

_ = require('underscore');

method = {
  GET: function(req, res, next) {
    return Product.find({}, function(err, products) {
      if (err) {
        return next(err);
      }
      return res.send(products);
    });
  },
  POST: function(req, res, next) {
    var id, product;
    delete req.body._id;
    if (id = req.params._id) {
      return Product.findById(id, function(err, product) {
        if (err) {
          return next(err);
        }
        _.extend(product, req.body);
        return product.save(function(err2) {
          if (err) {
            return next(err2);
          }
          Agent.find({}, function(err3, agents) {
            var agent, agentProduct, _i, _len, _results;
            if (err3) {
              console.log(err3);
            }
            _results = [];
            for (_i = 0, _len = agents.length; _i < _len; _i++) {
              agent = agents[_i];
              agentProduct = agent.products.id(product._id);
              agentProduct.name = product.name;
              agentProduct.unit = product.unit;
              _results.push(agent.save());
            }
            return _results;
          });
          return res.send(200);
        });
      });
    } else {
      product = new Product(req.body);
      return product.save(function(err) {
        if (err) {
          return next(err);
        }
        product.price *= 0.3;
        Agent.find({}, function(err2, agents) {
          var agent, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = agents.length; _i < _len; _i++) {
            agent = agents[_i];
            agent.products.push(product);
            _results.push(agent.save());
          }
          return _results;
        });
        return res.send(200);
      });
    }
  }
};

module.exports = function(req, res, next) {
  var e;
  try {
    return method[req.method](req, res, next);
  } catch (_error) {
    e = _error;
    console.log(e);
    return res.send(405);
  }
};

//# sourceMappingURL=product.map
