// Generated by CoffeeScript 1.6.3
(function() {
  var ProjectType, async, method;

  ProjectType = require('../models/projectTypeModel');

  async = require('async');

  method = {
    GET: function(req, res, next) {
      return ProjectType.find({}, null, {
        sort: '-_id'
      }, function(err, docs) {
        if (err) {
          console.log(err);
          return res.send(500);
        }
        return res.send(docs);
      });
    },
    POST: function(req, res, next) {
      var _ref;
      if ((_ref = req.user.role) !== 'leader' && _ref !== 'admin') {
        return res.send(403);
      }
      return async.auto({
        count: function(cb) {
          return ProjectType.count({
            name: req.body.name
          }, cb);
        },
        save: [
          'count', function(cb, rst) {
            if (rst.count > 0) {
              return res.send(500, '项目类型已经存在');
            }
            return ProjectType.create({
              name: req.body.name
            }, cb);
          }
        ]
      }, function(err, rst) {
        if (err) {
          console.log(err);
          return res.send(500);
        }
        return res.send(200);
      });
    },
    DELETE: function(req, res, next) {
      var _ref;
      if ((_ref = req.user.role) !== 'leader' && _ref !== 'admin') {
        return res.send(403);
      }
      return ProjectType.findById(req.params._id, function(err, doc) {
        if (!doc) {
          return res.send(404);
        }
        if (doc.projects > 0) {
          return res.send(500, '项目类型已经被使用，不能删除');
        }
        doc.remove();
        return res.send(200);
      });
    }
  };

  module.exports = function(req, res, next) {
    var e;
    try {
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      console.log(e);
      return res.send(405);
    }
  };

}).call(this);
