// Generated by CoffeeScript 1.6.3
(function() {
  var Project, method, _;

  Project = require('../models/projectModel');

  _ = require('underscore');

  method = {
    GET: function(req, res, next) {
      var filter, opts, _id, _ref;
      if (_id = req.params._id) {
        return Project.findById(_id, function(err, doc) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(doc);
        });
      } else {
        _ref = req.query, filter = _ref.filter, opts = _ref.opts;
        return Project.find(filter, null, opts, function(err, docs) {
          if (err) {
            console.log(err);
            return res.send(500);
          }
          return res.send(docs);
        });
      }
    },
    PUT: function(req, res, next) {
      var _id;
      if (!(_id = req.params._id)) {
        return res.send(400);
      }
      if (res.body._id) {
        delete res.body._id;
      }
      Project.update({
        _id: _id
      }, res.body, function() {});
      return res.send(200);
    },
    POST: function(req, res, next) {
      var doc;
      doc = new Project(req.body);
      return doc.save(function(err, doc) {
        if (err) {
          console.log(err);
          return res.send(500);
        }
        return res.send(200);
      });
    },
    DELETE: function(req, res, next) {
      var _id;
      if (!(_id = req.params._id)) {
        res.send(400);
      }
      return Project.findByIdAndRemove(_id, function(err) {
        if (err) {
          console.log(err);
          return res.send(500);
        }
        return res.send(200);
      });
    }
  };

  module.exports = function(req, res, next) {
    var e;
    try {
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      return res.send(405);
    }
  };

}).call(this);
