// Generated by CoffeeScript 1.6.3
(function() {
  var method;

  method = {
    GET: function(req, res, next) {},
    PUT: function(req, res, next) {},
    POST: function(req, res, next) {}
  };

  module.exports = function(req, res, next) {
    var e;
    try {
      return method[req.method](req, res, next);
    } catch (_error) {
      e = _error;
      console.log(e);
      return res.send(405);
    }
  };

}).call(this);
