// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectId, Schema, agentSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  agentSchema = new Schema({
    name: String,
    people: String,
    phone: String,
    projects: {
      type: Number,
      "default": 0
    }
  });

  module.exports = mongoose.model('Agent', agentSchema);

}).call(this);

//# sourceMappingURL=agentModel.map
