// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, agentSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  agentSchema = new Schema({
    name: String
  });

  module.exports = mongoose.model('Agent', agentSchema);

}).call(this);
