// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, areaSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  areaSchema = new Schema({
    name: String,
    managers: [
      {
        _id: ObjectId,
        name: String
      }
    ],
    parent: ObjectId
  });

  module.exports = mongoose.model('Area', areaSchema);

}).call(this);
