// Generated by CoffeeScript 1.7.1
var ObjectId, Schema, areaSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

ObjectId = Schema.Types.ObjectId;

areaSchema = new Schema({
  name: String,
  managers: [
    {
      _id: ObjectId,
      name: String
    }
  ],
  parent: ObjectId,
  projects: {
    type: Number,
    "default": 0
  }
});

module.exports = mongoose.model('Area', areaSchema);

//# sourceMappingURL=areaModel.map
