// Generated by CoffeeScript 1.7.1
var ID, ObjectId, Schema, clientSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

ObjectId = Schema.Types.ObjectId;

ID = require('./idModel');

clientSchema = new Schema({
  code: String,
  name: String
});

clientSchema.pre('validate', function(next) {
  var prefix, self;
  self = this;
  prefix = 'KH';
  return ID.getID(prefix, function(err, doc) {
    if (err) {
      return next(err);
    }
    self.code = String(doc.count);
    while (self.code.length < 6) {
      self.code = '0' + self.code;
    }
    self.code = prefix + self.code;
    return next();
  });
});

module.exports = mongoose.model('Client', clientSchema);

//# sourceMappingURL=clientModel.map
