// Generated by CoffeeScript 1.7.1
(function() {
  var ID, ObjectId, Schema, financeSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  ID = require('./idModel');

  financeSchema = new Schema({
    contract: {
      num: String,
      date: Date,
      price: Number,
      client: {
        _id: ObjectId,
        code: String,
        name: String
      },
      recvDate: Date,
      attachments: [String],
      payType: String
    },
    projects: [
      {
        type: ObjectId,
        ref: 'Project'
      }
    ],
    balance: {
      type: Number,
      "default": 0
    },
    memo: String,
    payments: [
      {
        money: Number,
        memo: String,
        date: Date
      }
    ],
    invoices: [
      {
        num: String,
        money: Number,
        memo: String,
        date: Date
      }
    ],
    notices: [
      {
        content: String,
        date: Date,
        readers: [
          {
            type: ObjectId,
            ref: 'User'
          }
        ]
      }
    ]
  });

  financeSchema.pre('validate', function(next) {
    var prefix, self;
    if (!this.isNew) {
      return next();
    }
    self = this;
    prefix = 'HT';
    return ID.getID(prefix, function(err, doc) {
      if (err) {
        return next(err);
      }
      self.contract.num = String(doc.count);
      while (self.contract.num.length < 6) {
        self.contract.num = '0' + self.contract.num;
      }
      self.contract.num = prefix + self.contract.num;
      return next();
    });
  });

  module.exports = mongoose.model('Finance', financeSchema);

}).call(this);

//# sourceMappingURL=financeModel.map
