// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, industrySchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  industrySchema = new Schema({
    name: String,
    projects: {
      type: Number,
      "default": 0
    }
  });

  module.exports = mongoose.model('Industry', industrySchema);

}).call(this);
