// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, industrySchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  industrySchema = new Schema({
    name: String
  });

  exports.Industry = mongoose.model('Industry', industrySchema);

  exports.industrySchema = industrySchema;

}).call(this);
