// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, mongoose, projectSchema;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.Types.ObjectId;

  projectSchema = new Schema({
    name: String,
    type: {
      _id: ObjectId,
      name: String
    },
    sales: {
      _id: ObjectId,
      name: String
    },
    area: {
      _id: ObjectId,
      name: String
    },
    company: {
      _id: ObjectId,
      name: String,
      manager: {
        _id: ObjectId,
        name: String
      }
    },
    industry: {
      _id: ObjectId,
      name: String
    },
    status: String,
    supporter: {
      _id: ObjectId,
      realname: String
    },
    tags: [String],
    agent: {
      _id: ObjectId,
      name: String
    },
    price: Number,
    buyYear: Number,
    client: String,
    orderDate: Date,
    mae: {
      account: String,
      pwd: String,
      creator: {
        _id: ObjectId,
        realname: String
      }
    },
    wx: {
      account: String,
      pwd: String,
      type: String
    },
    ec: {
      id: Number,
      sendBoxDate: Date
    },
    online: {
      date: Date,
      reviewer: {
        _id: ObjectId,
        name: String
      }
    },
    memo: String
  });

  module.exports = mongoose.model('Project', projectSchema);

}).call(this);
